import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practicesoftwaretesting.com/auth/register');
  await page.locator('[data-test="first-name"]').click();
  await page.locator('[data-test="first-name"]').press('CapsLock');
  await page.locator('[data-test="first-name"]').fill('Dennis');
  await page.locator('[data-test="last-name"]').click();
  await page.locator('[data-test="last-name"]').fill('silot');
  await page.locator('[data-test="dob"]').click();
  await page.locator('[data-test="dob"]').fill('1995-10-10');
  await page.locator('[data-test="street"]').click();
  await page.locator('[data-test="street"]').press('CapsLock');
  await page.locator('[data-test="street"]').fill('Olebush');
  await page.locator('[data-test="postal_code"]').click();
  await page.locator('[data-test="postal_code"]').fill('20152');
  await page.locator('[data-test="city"]').click();
  await page.locator('[data-test="city"]').press('CapsLock');
  await page.locator('[data-test="city"]').fill('Oleng');
  await page.locator('[data-test="state"]').click();
  await page.locator('[data-test="state"]').press('CapsLock');
  await page.locator('[data-test="state"]').fill('Nairobi');
  await page.locator('[data-test="country"]').selectOption('KE');
  await page.locator('[data-test="phone"]').click();
  await page.locator('[data-test="phone"]').fill('0705515471');
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').fill('kip@mail.com');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').press('CapsLock');
  await page.locator('[data-test="password"]').fill('Silot777@');
  await page.locator('[data-test="register-submit"]').click();
});