export const assertionText = {
  auth: {
    loginFormHidden: 'login form should not still be visible',
    otpPromptHidden: 'OTP prompt should not still be visible',
  },
  common: {
    downloadedFileMatchesExportType: 'downloaded file should match the export type',
    exportQueued: 'export should show a success message when the app queues the file generation',
    formDialogVisibleBeforeSaving: 'form dialog should be visible before saving',
  },
  locationManagement: {
    rowsBeforeSorting: (path: string) => `${path} should have rows before sorting`,
    sortableColumnVisible: (path: string) => `${path} should expose a sortable column`,
    rowsAfterSorting: (path: string) => `${path} should keep rows after sorting`,
    filterControlVisible: (path: string) => `${path} should expose a filter control`,
    filterPopupOpen: (path: string) => `${path} filter popup should open`,
    inputVisible: (fieldName: string) => `${fieldName} input should be visible`,
    optionAvailable: (fieldName: string, optionText?: string | RegExp) =>
      optionText ? `${fieldName} option "${optionText}" should be available` : `${fieldName} option should be available`,
  },
  rolesPermissions: {
    exportIconVisible: (exportIconName: RegExp) => `${exportIconName} export icon should be visible`,
    roleExists: (roleName: string | RegExp) => `role "${roleName}" should exist in the table`,
    roleAppears: (roleName: string | RegExp) => `role "${roleName}" should appear in the table`,
    permissionGroupExists: (name: string | RegExp) => `permission group "${name}" should exist`,
    permissionGroupExistsBeforeDeletion: (name: string | RegExp) => `permission group "${name}" should exist before deletion`,
    permissionGroupAppears: (name: string | RegExp) => `permission group "${name}" should appear in the table`,
    permissionGroupDeleted: (name: string | RegExp) => `permission group "${name}" should have been deleted`,
    permissionGroupDisplaysSavedPermissions: (name: string | RegExp) =>
      `permission group "${name}" should display saved permissions`,
    rowAppears: (name: string | RegExp) => `row "${name}" should appear in the table`,
    roleRowVisibleAfterDeactivation: 'role row should still be visible after deactivation',
    roleRowVisibleAfterReactivation: 'role row should be visible after reactivation',
    roleAvailable: 'at least one role should exist in the table',
    permissionGroupRowAfterPermissions: 'permission group row should still exist after adding permissions',
    rowAfterMultiplePermissionSets: 'row should exist after adding multiple permission sets',
    rowAfterDeactivation: 'row should exist after deactivation',
    rowAfterReactivation: 'row should exist after reactivation',
    statusSwitchAppears: 'status switch should appear',
    moduleSelectVisible: 'module select should be visible',
    confirmButtonAppears: 'confirm button should appear',
    viewOptionAppears: 'View option should appear in the row menu',
    nameInputAppears: 'name input should appear',
    addPermissionsActionVisible: 'Add Permissions action should be visible',
    permissionInputAppears: 'permission input should appear',
    nameInputForEditing: 'name input should appear for editing',
    deleteConfirmButtonAppears: 'delete confirm button should appear',
    rowActionButtonVisible: 'row action button should be visible',
    optionVisible: (option: string | RegExp) => `option "${option}" should be visible`,
    nextButtonEnabled: (stepName: string) => `"${stepName}" Next button should be enabled`,
  },
  userManagement: {
    existingEmailForDuplicate: 'existing user email should be available to verify duplicate handling',
    userRowAvailableToUpdate: 'a user row should be available to update',
    paginationNextAvailable: 'pagination next control should be available and enabled',
    existingEmailForSearch: 'existing user email should be available for search',
    filtersControlAvailable: 'filters control should be available',
    searchIncludes: (expectedText: string) => `search results should include "${expectedText}"`,
    searchExcludes: (term: string) => `search results should not include the missing term "${term}"`,
    rowsBeforeSorting: 'user table should have rows before sorting',
    sortControlAvailable: 'sort control should be available',
    rowsAfterSorting: 'user table should still have rows after sorting',
    exportButtonVisible: 'export button should be visible',
    exportOptionVisible: (label: RegExp) => `export option "${label}" should be visible`,
    exportControlVisible: (label: RegExp) => `export control for "${label}" should be visible`,
    dropdownOptionAvailable: (fieldName: string) => `${fieldName} option should be available`,
    placeholderGone: (fieldName: string) => `${fieldName} placeholder should disappear after selection`,
    activeUserAvailable: 'an active user row should be available to deactivate',
    inactiveUserAvailable: 'the same user row should be available to reactivate',
    rowActionMenuButtonVisible: 'row action menu button should be visible',
    statusSwitchVisible: 'status switch should be visible in row action menu',
  },
  masterData: {
    permissionGroupExistsAfterSetup: 'permission group should exist after setup',
  },
} as const;

export const assertionPatterns = {
  auth: {
    loginOrSignIn: /login|sign in/i,
  },
  common: {
    exportStarted: /export started successfully|exported successfully|download started/i,
    popup: /.*/,
  },
  userManagement: {
    successSaved: /success|created|saved/i,
    duplicateEmail: /email already in use|already registered|duplicate/i,
    invalidEmail: /valid email|invalid email|please enter.*email/i,
    characterLimit: /maximum|max length|too long|characters/i,
    activityLog: /activity log|audit log|user actions/i,
    activeUsers: /active users/i,
    totalUsers: /total users/i,
    totalRoles: /total roles/i,
    firstNameValue: /\S+/,
  },
  rolesPermissions: {
    inactive: /inactive/i,
    active: /active/i,
    permissionSummary: /create|edit|view/i,
    assignedPermissions: /assigned permissions/i,
  },
} as const;
