name: Workflow caller

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: Target Env
        type: choice
        options: [PRODUCTION, DEV]
        default: PRODUCTION

jobs:
  run-playwright-tests:
    uses: ./.github/workflows/itibari-reusable.yaml

    with:
      tag: ""
      environment: ${{ inputs.environment || 'PRODUCTION' }}
      shardIndex: 1
      shardTotal: 4
      node-version: 24.x
      use-cache: true

    secrets:
      ADMIN_TOKEN: ${{ secrets.PROD_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ITIBARI_USERNAME: ${{ secrets.ITIBARI_USERNAME }}
      ITIBARI_PASSWORD: ${{ secrets.ITIBARI_PASSWORD }}
      ITIBARI_TOTP_SECRET: ${{ secrets.ITIBARI_TOTP_SECRET }}
      PLAYWRIGHT_AUTH_STATE_BASE64: ${{ secrets.PLAYWRIGHT_AUTH_STATE_BASE64 }}
